const A = 'assets';

export const CORE_ASSETS = Object.freeze({
  bgAlley: `${A}/backgrounds/bg_alley_2.png`,
  bgPerfectGrape: `${A}/backgrounds/bg_perfect_grape.png`,
  bgNoGrape: `${A}/backgrounds/bg_no_grape.png`,
  bgOffice1: `${A}/backgrounds/bg_office_1.png`,
  bgOffice2: `${A}/backgrounds/bg_office_2.png`,
  bgHearingRoom: `${A}/backgrounds/bg_hearing_room.png`,
  jimothyIdle: `${A}/characters/jimothy/jimothy_walk_01.png`,
  jimothyInteract: `${A}/characters/jimothy/jimothy_interact.png`,
  jimothyWalk1: `${A}/characters/jimothy/jimothy_walk_01.png`,
  jimothyWalk2: `${A}/characters/jimothy/jimothy_walk_02.png`,
  jimothyWalk3: `${A}/characters/jimothy/jimothy_walk_03.png`,
  jimothyWalk4: `${A}/characters/jimothy/jimothy_walk_04.png`,
  jimothyInteriorIdle: `${A}/characters/jimothy/jimothy_interior_idle_stand.png`,
  jimothyInteriorWalk1: `${A}/characters/jimothy/jimothy_interior_walk_01.png`,
  jimothyInteriorWalk2: `${A}/characters/jimothy/jimothy_interior_walk_02.png`,
  jimothyInteriorWalk3: `${A}/characters/jimothy/jimothy_interior_walk_03.png`,
  jimothyInteriorWalk4: `${A}/characters/jimothy/jimothy_interior_walk_04.png`,
  jimothyVestInteriorIdle: `${A}/characters/jimothy/jimothy_vest_interior_idle_stand.png`,
  jimothyVestInteriorInteract: `${A}/characters/jimothy/jimothy_vest_interior_interact.png`,
  jimothyVestInteriorHiss: `${A}/characters/jimothy/jimothy_vest_interior_hiss.png`,
  jimothyFeralInteriorInteract: `${A}/characters/jimothy/jimothy_feral_interior_interact.png`,
  jimothyEat: `${A}/characters/jimothy/jimothy_eat.png`,
  jimothyVestInteriorWalk1: `${A}/characters/jimothy/jimothy_vest_interior_walk_01.png`,
  jimothyVestInteriorWalk2: `${A}/characters/jimothy/jimothy_vest_interior_walk_02.png`,
  jimothyVestInteriorWalk3: `${A}/characters/jimothy/jimothy_vest_interior_walk_03.png`,
  jimothyVestInteriorWalk4: `${A}/characters/jimothy/jimothy_vest_interior_walk_04.png`,
  clerkIdle: `${A}/characters/npcs/clerk_idle.png`,
  clerkTalk: `${A}/characters/npcs/clerk_talk.png`,
  clerkPaperwork: `${A}/characters/npcs/clerk_paperwork.png`,
  clerkGiantForm: `${A}/characters/npcs/clerk_giant_form.png`,
  clerkPanic: `${A}/characters/npcs/clerk_panic.png`,
  beaverIdle: `${A}/characters/npcs/beaver_idle.png`,
  beaverTalk: `${A}/characters/npcs/beaver_talk.png`,
  beaverStamp: `${A}/characters/npcs/beaver_stamp.png`,
  beaverHorrified: `${A}/characters/npcs/beaver_horrified.png`,
  financeBroIdle: `${A}/characters/npcs/finance_bro_idle.png`,
  financeBroPanic: `${A}/characters/npcs/finance_bro_panic.png`,
  crowIdle: `${A}/characters/npcs/crow_idle.png`,
  crowTalk: `${A}/characters/npcs/crow_talk.png`,
  crowPanic: `${A}/characters/npcs/crow_panic.png`,
  squirrelIdle: `${A}/characters/npcs/squirrel_idle.png`,
  pigeonIdle: `${A}/characters/npcs/pigeon_idle.png`,
  dumpsterClosed: `${A}/props/dumpster_closed.png`,
  dumpsterOpen: `${A}/props/dumpster_lid_open.png`,
  dumpsterNotice: `${A}/props/dumpster_notice.png`,
  crumpledReceipt: `${A}/props/crumpled_up_receipt.png`,
  leaf: `${A}/props/leaf.png`,
  takeoutBox: `${A}/props/takeout_box.png`,
  unopenedMail: `${A}/props/unopened_mail.png`,
  theCone: `${A}/props/the_cone.png`,
  officeCounter: `${A}/props/office_counter.png`,
  ticketMachine: `${A}/props/office_ticket_machine.png`,
  ticketScreen: `${A}/props/office_ticket_counter_screen.png`,
  sadPlant: `${A}/props/office_sad_counter_plant.png`,
  happyPlant: `${A}/props/office_happy_counter_plant.png`,
  serviceBell: `${A}/props/service_bell.png`,
  form8B: `${A}/props/form.png`,
  form12C: `${A}/props/long_form.png`,
  chainedPen: `${A}/props/chained_pen.png`,
  formStack: `${A}/props/form_stack.png`,
  fileStack: `${A}/props/file_stack.png`,
  hugeFormStack: `${A}/props/huge_form_stack.png`,
  municipalStamp: `${A}/props/munincipal_stamp.png`,
  approvedStamp: `${A}/props/approved_stamp.png`,
  deniedStamp: `${A}/props/denied_stamp.png`,
  returnedStamp: `${A}/props/returned_stamp.png`,
  voidStamp: `${A}/props/void_stamp.png`,
  municipalKey: `${A}/props/key.png`,
  dracaena: `${A}/props/dracaena.png`,
  banana: `${A}/props/banana.png`,
  tinfoilBall: `${A}/props/tinfoil_ball.png`,
  spoon: `${A}/props/spoon.png`,
  refuseBin: `${A}/props/bin.png`,
  recycleBin: `${A}/props/recycle_bin.png`,
  officeChair: `${A}/props/office_chair.png`,
  officeDesk: `${A}/props/office_desk.png`,
});

const audioSources = (folder, name) => [
  `${A}/audio/${folder}/${name}.ogg`,
  `${A}/audio/${folder}/${name}.mp3`,
];

export const AUDIO_ASSETS = Object.freeze({
  alleyAmbience: audioSources('ambience', 'alley'),
  officeAmbience: audioSources('ambience', 'office'),
  bell: audioSources('sfx', 'bell'),
  coneKick: audioSources('sfx', 'cone-kick'),
  coneMove: audioSources('sfx', 'cone-move'),
  cronchGrape: audioSources('sfx', 'cronch-grape'),
  deskCrash: audioSources('sfx', 'desk-crash'),
  dumpsterDive: audioSources('sfx', 'dumpster-dive'),
  dumpsterOpen: audioSources('sfx', 'dumpster-lid'),
  eatForm: audioSources('sfx', 'eat-form'),
  formSwoosh: audioSources('sfx', 'form-swoosh'),
  inventoryUpdated: audioSources('sfx', 'inventory-updated'),
  penChain: audioSources('sfx', 'pen-chain'),
  rageSting: audioSources('sfx', 'rage-sting'),
  stamp1: audioSources('sfx', 'stamp-1'),
  stamp2: audioSources('sfx', 'stamp-2'),
  uiClick: audioSources('sfx', 'ui-click'),
  vestEquip: audioSources('sfx', 'vest-equip'),
  yayGrape: audioSources('sfx', 'yay-grape'),
  rageMusic: [`${A}/audio/music/future-anno-domini-beats.mp3`],
});
