export const GAME_WIDTH = 2048;
export const GAME_HEIGHT = 1152;

export const DEPTH = Object.freeze({
  background: 0,
  behindFurnitureNpc: 10,
  furniture: 20,
  countertopProp: 30,
  prop: 40,
  actor: 50,
  effect: 60,
  ui: 100,
});

export const INITIAL_STATE = Object.freeze({
  personalObjective: 'GET GRAPE',
  currentObjective: 'INVESTIGATE DUMPSTER',
  flags: {
    dumpsterOpened: false,
    grapeSeen: false,
    grapeAttempted: false,
    clerkInterrupted: false,
    permitOfficeUnlocked: false,
    enteredPermitOffice: false,
    clerkAskedForNumber: false,
    hasTicket033: false,
    number033Called: false,
    hasForm8B: false,
    needsResidencyProof: false,
    hasLeaf: false,
    coneMovedEarly: false,
    coneMovedByCity: false,
    hasNotarizedLeaf: false,
    taxDebtKnown: false,
    sanitationOfficeUnlocked: false,
    vestEquipped: false,
    bananaSorted: false,
    foilSorted: false,
    spoonSorted: false,
    spoonWarned: false,
    sanitationComplete: false,
    hasSanitationCertification: false,
    hasDollarThirteen: false,
    hasMunicipalKey: false,
    taxPaid: false,
    needsJurisdictionReview: false,
    hearingComplete: false,
    form12Presented: false,
    feralMode: false,
    form12PartiallyEaten: false,
    form12Submitted: false,
    deskTaken: false,
    hasMunicipalStamp: false,
    coneMovedFeral: false,
    grapeAcquired: false,
    endingComplete: false,
  },
});
